# Generated by Django 3.1.6 on 2021-03-17 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210314_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie.movie')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userNoti_from', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userNoti_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
