# Generated by Django 3.1.6 on 2021-03-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210314_1218'),
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie.movie'),
        ),
    ]
