# Generated by Django 3.1.6 on 2021-03-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210301_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='gerne_ids',
            field=models.ManyToManyField(blank=True, to='movie.Gerne'),
        ),
    ]
